@startuml domain-model
skinparam packageStyle rectangle

/'
package タスク集約 {
    object "タスク" as task {
        タスクID
        名前
        期日
        担当ユーザーID
    }
}

package ユーザー集約 {
    object "ユーザー" as user {
        ユーザーID
        ユーザー名
        ステータス
    }
}

task::ユーザーID --> user : ユーザーID参照
'/

object "ファイルシステム" as fileSystem

object "PATH マネージャ" as pathManager

object "キャッシュマネージャ" as cacheManager

object "cljstyle バージョン取得元" as versionSource

object "cljstyle ダウンロード元" as binarySource

object "cljstyle バイナリ" as binary
@enduml
