name: Lint

on:
  push:
    branches-ignore:
      - 'release/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: PureScript Lint
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl https://mise.jdx.dev/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      - run: mise plugin install pnpm https://github.com/jonathanmorley/asdf-pnpm
      - run: mise install
      - run: pnpm install
      - run: pnpm lint
