name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    name: PureScript Lint
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.19.1
          run_install: true
      - run: pnpm lint
