name: Test

on: push

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cljstyle-version: 0.13.0
      - run: cljstyle version

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cljstyle-version: 0.13.0
      - run: cljstyle version
