name: Test

on:
  push:
    branches-ignore:
      - 'release/**'

jobs:
  purs-test:
    runs-on: ubuntu-latest
    name: PureScript Test
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.19.1
          run_install: true
      - run: pnpm test
