name: Use this action

on:
  push:
    branches:
      - 'release/**'

jobs:
  use-on-linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          run-check: true
      # - run: cljstyle version
